# https://travis-ci.org/jazzband/django-oauth-toolkit
dist: xenial

language: python

matrix:
    include:
      - python: 3.4
        env: TOX_ENV=py34-django20
      - python: 3.4
        env: TOX_ENV=py34-django21
      - python: 3.4
        env: TOX_ENV=py34-django22
      - python: 3.5
        env: TOX_ENV=py35-django20
      - python: 3.5
        env: TOX_ENV=py35-django21
      - python: 3.5
        env: TOX_ENV=py35-django22
      - python: 3.6
        env: TOX_ENV=py36-django20
      - python: 3.6
        env: TOX_ENV=py36-django21
      - python: 3.6
        env: TOX_ENV=py36-django22
      - python: 3.7
        env: TOX_ENV=py37-django20
      - python: 3.7
        env: TOX_ENV=py37-django21
      - python: 3.7
        env: TOX_ENV=py37-django22

cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/.tox

install:
  - pip install coveralls tox tox-travis

script:
  - tox -e $TOX_ENV

after_script:
  - coveralls
